AllCops:
  TargetRubyVersion: 2.5.1

Metrics:
  Enabled: false

Metrics/LineLength:
  Max: 99
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

# to support Ruby 2.2
Style/NumericPredicate:
  Enabled: false
