# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1 

jobs:
  test:
    parameters:
      v:
        default: "2.7.4" # Latest version
        type: string
    working_directory: ~/sidekiq_fast_debounce
    docker:
      - image: circleci/ruby:<< parameters.v >>
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle check --path vendor/bundle || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Make test-results
          command: |
            mkdir /tmp/test-results

      - run:
          name: Run basic specs
          command: |
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec-basic.xml \
                            --format progress \
                            spec

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  deps:
    docker:
      - image: circleci/ruby:2.7.4
    working_directory: ~/sidekiq_fast_debounce

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "sidekiq_fast_debounce.gemspec" }}

      - run:
          name: install dependencies
          command: |
            bundle check --path vendor/bundle || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v2-dependencies-{{ checksum "sidekiq_fast_debounce.gemspec" }}

      - run:
          name: dependencies security audit
          command: |
            bundle exec bundle-audit check --update

      - run:
          name: Rubocop
          command: bundle exec rubocop

  generate_docs:
    docker:
      - image: circleci/ruby:2.7.4
    working_directory: ~/sidekiq_fast_debounce

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "sidekiq_fast_debounce.gemspec" }}

      - run:
          name: Setup bundler path
          command: |
            bundle check --path vendor/bundle

      - run:
          name: Generate Yard docs
          command: |
            bundle exec yard --output-dir /tmp/workspace/docs/yard

      - run:
          name: Num Docs
          command: |
            ls -al /tmp/workspace/docs/yard | wc -l

      - persist_to_workspace:
          root: /tmp/workspace/docs
          paths:
            - yard
  deploy:
    docker:
      - image: circleci/ruby:2.7.4
    working_directory: ~/sidekiq_fast_debounce
    steps:
      - checkout

      - run:
          name: Deploy to RubyGems.org
          command: gem push

workflows:
  test-and-deploy:
    jobs:
      - deps
      - test:
          name: "ruby-2.7.4"
          v: "2.7.4"
          requires:
            - deps
      - test:
          name: "ruby-2.6"
          v: "2.6"
          requires:
            - deps
      - test:
          name: "ruby-2.5"
          v: "2.5"
          requires:
            - deps
      - generate_docs:
          requires:
            - ruby-2.7.4
            - ruby-2.6
            - ruby-2.5
      - deploy:
          requires:
            - deps
            - generate_docs
